# Define pipeline stages
stages:
  - docker_image_build
  - docker_image_push
  - deploy

# Build Docker image
docker_image_build:
  stage: docker_image_build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_USER/my_app:latest .  
  only:
    - Project-4
  tags:
    - dev

# Push Docker image to the registry
docker_image_push:
  stage: docker_image_push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD  
    - docker image tag mevikash/my_app:latest $CI_REGISTRY_USER/my_app:latest
    - docker push $CI_REGISTRY_USER/my_app:latest  
  only:
    - Project-4
  tags:
    - dev

# Deploy with Docker Compose
deploy:
  stage: deploy
  script:
    - sudo docker-compose down
    - sudo docker-compose up -d
  only:
    - Project-4
  tags:
    - dev
