apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
  namespace: webapplication
  labels:
    app: web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-application
  template:
    metadata:
      name: web-application
      labels:
        app: web-application
    spec:
      containers:
        - name: web-application
          image: mevikash/web-application:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-application
  namespace: webapplication
spec:
  type: NodePort
  selector:
    app: web-application
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 31000
